### ISSUE TITLE
feature request: draw the dots on the fingerboard 

### ISSUE THREAD

**Issue by stoyan** [omnibrain/svguitar#111]
...to make it easier to orient. 

Default: subtle grey dots, smaller then the finger circles on frets 3, 5, 7, 9. And two on fret 12. Fender-like :)

**Comment by omnibrain** [comment]
I appreciate your suggestion! I’ll definitely implement it, but it might take a few weeks or months. I’m quite swamped with other things right now

**Comment by omnibrain** [comment]
It's implemented: https://github.com/omnibrain/svguitar/pull/114

I will merge it soon. Here's an example:

![fret-markers-horizontal](https://github.com/user-attachments/assets/60ca6fac-2d07-4ad2-8135-816455630ed0)

Fret markers are highly customizable: Shape, color, size, etc. can be configured globally and overridden for each marker.

**Comment by omnibrain** [comment]
This is now available from version 2.3.0: https://github.com/omnibrain/svguitar/releases/tag/v2.3.0

**Comment by stoyan** [comment]
Perfect, thank you!
