### ISSUE TITLE
Starting to build a Lit.js web component wrapper 

### ISSUE THREAD

**Issue by parent-tobias** [omnibrain/svguitar#113]
So I'm building a larger `chordPro` editor/ display project, and started from a chord diagram web component. I'm using lit, and a very basic music theory model. I'm still refining it, long way to go, but feel free to fork and extend. 

<https://github.com/parent-tobias/lit-gigwidget>

**Comment by omnibrain** [comment]
I love it! Once you feel like it's ready to share with people let me know and I'll add it to the [Projects using SVGuitar
](https://github.com/omnibrain/svguitar?tab=readme-ov-file#projects-using-svguitar) in the Readme.

**Comment by parent-tobias** [comment]
Cool, thank you! I'll keep you posted!
