### ISSUE TITLE
All chords data needed

### ISSUE THREAD

**Issue by yigithanyucedag** [omnibrain/svguitar#25]
Is there anyone has parameters(fingers, barres, title,...) of all chords in this library format?

**Comment by omnibrain** [comment]
Sorry I don‘t understand your question. You can see all available parameters in the README.md, as well as in the TypeScript documentation available here: https://omnibrain.github.io/svguitar/docs/

**Comment by yigithanyucedag** [comment]
I need json data of all chords(Am, G, Em, ...). I thought anyone who made it before can help me.

**Comment by omnibrain** [comment]
Ah ok now I get it. Unfortunately I don‘t have a list of chords, but the vexchords library has almost the same API and they have a list of chords here: https://github.com/0xfe/vexchords/blob/master/static/demo.html

Maybe that helps.
