### ISSUE TITLE
Incorrect chord in README example

### ISSUE THREAD

**Issue by jeffreysbrother** [omnibrain/svguitar#33]
The first example chord is listed as "G major" but it is actually a "D major".

Additionally, there are two potential issues with the second SVG example: 1) there is no name given so it's unclear whether the intention was to illustrate an alternative way to play "G major" (which it is not) or simply to illustrate that it's optional to provide no name, 2) the chord itself is a pretty unpalatable one, so a beginner might decide to stop playing music entirely after hearing the horror that radiates upon strumming the instrument. I suggest a B flat minor as an alternative (which can be obtained by shifting every note one string westward).

**Comment by omnibrain** [comment]
Thank you for this valuable feedback @jeffreysbrother . As you may have noticed I am not a guitar player. To me it's all just circles and rectangles and stuff. 

I replaced the images with new ones.
