### ISSUE TITLE
Incorrect screenshot in README?

### ISSUE THREAD

**Issue by zorn** [omnibrain/svguitar#34]
Incorrect screenshot in README?

https://twitter.com/agiletortoise/status/1273269559395524608

**Comment by zorn** [comment]
<img width="610" alt="Screen Shot 2020-06-18 at 7 47 33 PM" src="https://user-images.githubusercontent.com/52168/85082327-928dc300-b19c-11ea-845d-504c3e108e61.png">

**Comment by omnibrain** [comment]
Thanks for letting me know @zorn , I created a new image with a correct title
