### ISSUE TITLE
[Talking] - Can we always placed that header space ?

### ISSUE THREAD

**Issue by imiskolee** [omnibrain/svguitar#42]
As the blow screenshot, the right svg chord height less than left, beacuse the right svg hasn't any header elements.(x or O).
but i think always keep the header space is better.
 
![image](https://user-images.githubusercontent.com/4303880/99896959-4e18cd00-2cd0-11eb-9404-1d57232bc9bf.png)

**Comment by omnibrain** [comment]
There is already an option for that: https://omnibrain.github.io/svguitar/docs/interfaces/chordsettings.html#fixeddiagramposition

Just set this to true and the diagram will always be at the same position, even without X‘s or O‘s at the top.

**Comment by imiskolee** [comment]
@omnibrain yes. it's working, and i cosed it.
