### ISSUE TITLE
title and position shoud be part of the chord, not part of the configuration 

### ISSUE THREAD

**Issue by Aduffy** [omnibrain/svguitar#43]
It seems to me that the title and position values should be passed as part of the chord object its self and not as part of the configuration... 

![image](https://user-images.githubusercontent.com/265857/100394852-761b6f80-2ff3-11eb-9860-5e6cd68f58dc.png)

**Comment by omnibrain** [comment]
Great suggestion, this is now implemented in version 1.10.0
