### ISSUE TITLE
Individual note styling 

### ISSUE THREAD

**Issue by Aduffy** [omnibrain/svguitar#44]
Is there a way to style individual dots (notes) in a chord? For example I would like to use different colors for the different interval values or to highlight the root note. 

I know I can do this using the main color option when defining the chord, but can this be done by setting color in the configuration to be a function that receives the string and fret etc..  

for example i can do this with fretboard.js  (https://moonwave99.github.io/fretboard.js/documentation-fretboard.html ) 

`dotFill: ({ interval }) => getInColor(interval),`

**Comment by omnibrain** [comment]
Yes, you can set options on individual notes and barres, take a  look at the available options here: https://omnibrain.github.io/svguitar/docs/interfaces/fingeroptions.html

Take for example this configuration: 

```javascript
const chord = {
  fingers: [
    [
      1,
      2,
      {
        color: 'red'
      }
    ],
    [
      2,
      3,
      {
        color: 'blue'
      }
    ]
  ],
  barres: []
}
new SVGuitarChord('#chart')
          .chord(chord)
          .draw();
```

This will result in the following chord diagram:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/2551508/100514128-59597600-3172-11eb-8e5d-cbb1cf3c6b47.png">
