### ISSUE TITLE
Feature Request - strokeColor / strokeWidth 

### ISSUE THREAD

**Issue by Aduffy** [omnibrain/svguitar#46]
It would be nice if we could define a per note stroke color / width in the same way as adding a bg color 

`[4, 4, { text: "4", color: "#fff", strokeColor: "#000" }]`

**Comment by omnibrain** [comment]
This is now implemented and available from version 1.11.0. Should be available as soon as the build is complete (ca. 1-2 hours).

**Comment by Aduffy** [comment]
Rock Star!

**Comment by omnibrain** [comment]
FYI i made a small API change: Before the change i just pushed the options on the notes were called `nutStrokeColor` and `nutStrokeWidth`. Now they are just called `strokeColor` and `strokeWidth`, just as you porposed. 

The global configuration (that is passed to `configure()`) is still called `nutStrokeWidth` and `nutStrokeColor`.
