### ISSUE TITLE
nutTextColor  not working

### ISSUE THREAD

**Issue by Aduffy** [omnibrain/svguitar#47]
Setting the color of the note (nut) text does not seem to have effect. Text is always white 

```javascript
    .configure({ nutTextColor: '#000' })
```

**Comment by omnibrain** [comment]
This is the default text color of nuts. By setting colors on individual fingers you are overriding this global configuration.

**Comment by omnibrain** [comment]
Oops, actually you're right, that's a bug. I will fix it shortly

**Comment by Aduffy** [comment]
Thanks.. Also took me a while to realize that 'nut' refers to each of the note dots and not the "Nut" that is between the fretboard and the headstock.. wouldn't noteTextColor been a better name?
