### ISSUE TITLE
Draw dots on top of barres

### ISSUE THREAD

**Issue by Aduffy** [omnibrain/svguitar#48]
If a finger dot and a barre are both defined on the same place, than the dot is UNDER the barre. The dot should be rendered on top of the barre.. 

I know in most cases one would not need to see that since the barre is repeating same note to hold down but in my case I am trying to show the chord notes with the interval or the note name 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/265857/100571613-68cae300-3288-11eb-8c1d-b65905238571.png">

If you look close you can see the yellow (R) note peeking out under the top of the bar.

**Comment by omnibrain** [comment]
So do I understand correctly that all you want is to render single fingers on top of the barres?

**Comment by omnibrain** [comment]
OK I made this change as you are probably the only person affected by this. So even if I missunderstood there's no harm done :)

**Comment by Aduffy** [comment]
Thanks!  It does come in handy in my case where I want to draw ALL of the notes played with the interval name (and color). 

I did manage to hack my UMD build to get what i was looking for as well as adding a stroke to the notes so i could end up with this 

![image](https://user-images.githubusercontent.com/265857/101822367-11294480-3ade-11eb-9cb3-1d1448d50ea8.png)

**Comment by omnibrain** [comment]
Looks good! But now you could also use the official library without hack. Whatever you prefer :)

I also just pushed a version where you can set the stroke width and color for both nuts and barre chords, should be released in 1-2 hours as soon as the build completes.

**Comment by Aduffy** [comment]
Ya I would much prefer to keep to a non hacked build! Thank you so much for implementing these changes for me!
