### ISSUE TITLE
Support chart rotation

### ISSUE THREAD

**Issue by veedubyou** [omnibrain/svguitar#56]
Hi, firstly thank you for this library! It's incredibly cool and the API is really thoughtful and a joy to use.

I'd like to ask if rotating the chart as an option is possible. Usecase is drawing scale diagrams - although this is a chord diagram library, the way the fingers are defined already lends itself to easily make a scale diagram, however, they tend to be read from above the neck:

![image](https://user-images.githubusercontent.com/5819893/112916583-b2500100-90b5-11eb-96b2-355a00a00e76.png)

I could CSS rotate the diagram myself, but some other things will be out of whack, notably any text titles or text (e.g. scale degrees) on the fingering. Ofc I'm also open to any other solution that can solve this problem.

**Comment by omnibrain** [comment]
Sorry for the late reply. I'm glad to hear that you enjoy using this library!

Great workaround @textchimp and I'm super happy to see the new naming system already being put to good use.

I now implemented this as a feature, you can now pass `orientation: vertical` to change the orientation: 

```javascript
svguitar
      .chord({
        // ...
      })
      .configure({
        // ... other settings
        orientation: 'horizontal'
      })
      .draw()
```

This will create diagrams like this:

![image](https://user-images.githubusercontent.com/2551508/149637178-48640e69-ab06-4ad5-9e9c-baca255d4a0d.png)
