### ISSUE TITLE
Generate Images browserless

### ISSUE THREAD

**Issue by TormodKv** [omnibrain/svguitar#74]
May be a stupid question, but this already supported?
I haven't found any documentation for it. 
It doesn't look like jsdom can do the trick (for me anyways).

**Comment by omnibrain** [comment]
Not a stupid question at all. I'm actually using JSDom for some visual tests (see https://github.com/omnibrain/svguitar/blob/master/test/svguitar.test.ts), so it *kind of* works, but unfortunately it has some problems, eg for some reason the positioning of text is a bit different. Also I didn't get roughjs (used for the hand-drawn diagrams) to work with JSDom. 

So to answer your question: No, it's not supported but it might work if someone would spend some time on it :) Unfortunately I don't have the time at the moment...

**Comment by TormodKv** [comment]
While running your tests, i get almost the exact same error as i got earlier with JSDom:
TypeError: `Cannot read properties of null (reading 'attr')`
`this.svg.attr('preserveAspectRatio', 'xMidYMid meet').viewbox(0, 0, width, height)`
at `new SvgJsRenderer (src/renderer/svgjs/svg-js-renderer.ts:30:14)`

**Comment by omnibrain** [comment]
You're right, the tests didn't run anymore! Apparently an update of @svgdotjs/svg.js broke it. I dongraded @svgdotjs/svg.js to a slightly older version for now and I'll try to figure out what's causing the error with the current version when I have some time. 

Can you pull the newest version and check if it works for you now?

**Comment by TormodKv** [comment]
Works perfectly!

Thank you
