### ISSUE TITLE
Adding muted.io to list of projects

### ISSUE THREAD

**Issue by thisisseb** [omnibrain/svguitar#92]
Hi there,

Great project! I'm making use of it on muted.io on chord pages like this one: https://muted.io/d-major-chord/

I thought I'd share in case it would be a good addition to the list of projects making use of SVGuitar.

Thanks a bunch!
Seb

**Comment by omnibrain** [comment]
Very cool website! I love seeing SVGuitar in good use. 

Will be added to the list shortly.
