### ISSUE TITLE
Vertical offset bug

### ISSUE THREAD

**Issue by vallica** [omnibrain/svguitar#94]
Hi,

Thanks for this awesome lib ! 👍 

I just encounter this kind of vertical offset bug :

![image](https://user-images.githubusercontent.com/9962981/199541958-a44e406a-b576-4d42-84a6-6bad9109954c.png)

however all my dom elements have same style 
![image](https://user-images.githubusercontent.com/9962981/199542471-1f3a6d60-9e19-4428-89cc-871beeae5a2c.png)

Cheers

**Comment by vallica** [comment]
PS : it seems not linked to the "title" option :

![image](https://user-images.githubusercontent.com/9962981/199543180-ea194441-3e2d-4b9e-8806-bdb4b1abd6de.png)

**Comment by vallica** [comment]
PS2 : another cases in order to help debug 

![image](https://user-images.githubusercontent.com/9962981/199546020-f0e1e160-6d5c-4862-b9a4-f7d1abefbbe2.png)

![image](https://user-images.githubusercontent.com/9962981/199546229-a41d690a-12e0-48d2-b8ff-5332e62049f2.png)

![image](https://user-images.githubusercontent.com/9962981/199546441-709d997d-0ad0-4892-bf94-e4d570a63705.png)

**Comment by omnibrain** [comment]
Hi @vallica, thanks for reporting this. Could you share the configuration of one chart with an incorrect vertical offset?

**Comment by omnibrain** [comment]
The second value of the fingers should also be of type number. 

So instead of `[1, '0']` it should be `[1, 0]`. 

Can you try that and see if that fixes the problem?

**Comment by vallica** [comment]
All is right !

![image](https://user-images.githubusercontent.com/9962981/199554832-b267b28d-d52e-4b77-802a-7a8980e7cc6c.png)

Thanks a lot, my apologies for the inconvenience

**Comment by omnibrain** [comment]
No worries, glad I could help.
